### ISSUE TITLE
Individual issues/PRs in GitHub widgets should have rounded corners

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#116] opened 2023-05-18 17:54 UTC
### Steps to reproduce the bug

Description
Hovering over an individual item in a GitHub Issues widget highlights the item from side to side in the whole widget box with no padding. I would expect some left-right padding for this highlight (and also expected the individual issue items to have rounded corners).

**Comment by krschau** [comment] 2023-05-23 15:28
Padding was added, but corners are not rounded.

**Comment by krschau** [comment] 2023-08-31 20:47
Duplicate of https://github.com/microsoft/devhome/issues/1465

**Closed by krschau** 2023-08-31 20:47 UTC
Labels: Area-Widgets, Issue-Task, Priority-2, Area-Style
