### ISSUE TITLE
Widgets Losing State When I Relaunch Dev Home

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhomegithubextension#336] opened 2024-01-30 15:48 UTC
### Dev Home version

0.901.374.0

### Windows build number

23620

### Steps to reproduce the bug

I have pinned widgets in this configuration: 

![image](https://github.com/microsoft/devhomegithubextension/assets/98557455/a5c43903-5200-46af-a86e-126f14ed7359)

The two widgets that aren't customized were previously customized with URL queries.

1. Pin a few GH widgets 
2. Finish customization
3. Relaunch Dev Home
4. Navigate to Dashboard

### Expected result

The widget should be in the same configured state that I had previously had it.

### Actual result

The widget state appears to be unconfigured and I've lost the URL query I had previously used.

**Comment by joadoumie** [comment] 2024-01-30 15:50
For more information, I just was able to reproduce this without closing Dev Home. I left the dashboard and returned to it and now I've lost state for the third widget: 

![image](https://github.com/microsoft/devhomegithubextension/assets/98557455/76219a1a-edb5-4b1a-be6c-17007c5cbcba)

**Comment by krschau** [comment] 2024-01-31 15:28
What version of the extension did you have when this happened?

**Comment by joadoumie** [comment] 2024-02-06 02:56
I had the latest version at that point in time.

**Comment by krschau** [comment] 2024-02-12 23:33
Lowering priority since it's not particularly common.

**Comment by krschau** [comment] 2024-02-15 16:52
Duplicate of #348

(Higher issue number, but actually older since it was transferred from other repo)

**Closed by krschau** 2024-02-15 16:52 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
