### ISSUE TITLE
[Issues Widget] Order not consistent

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/devhomegithubextension#253] opened 2023-10-26 18:49 UTC
### Dev Home version

0.601.285.0

### Windows build number

10.0.22621.0

### Steps to reproduce the bug

Despite having Dev Home showing order in the query, issues aren't sorted in the widget.

URL: https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue+label%3A%22Product-Hosts+File+Editor%22+sort%3Acreated-desc

<img width="960" alt="image" src="https://github.com/microsoft/devhomegithubextension/assets/25966642/4e224e83-7132-43d1-a68e-003b13ef23b5">

<img width="238" alt="image" src="https://github.com/microsoft/devhomegithubextension/assets/25966642/508a9891-0863-49cb-8df6-1d616475f0d9">

### Expected result

Issues should be sorted by creation date descending.

### Actual result

Issues aren't sorted.

**Comment by krschau** [comment] 2023-10-31 15:15
@dkbennett FYI

**Comment by dkbennett** [comment] 2023-11-04 21:42
The collection of issues returned is already in sorted order descending by creation date. The image of the widget display in the issue description is also in correct sorted order.

I see the issues created 346, 347 and 350 days ago in the issue display, which is in descending order by creation date.

I also checked my own issues widgets and the issues are correctly sorted there too. I don't see any issue here neither in the provided image nor on my own widgets, so closing as not repro.

**Comment by davidegiacometti** [comment] 2023-11-04 23:01
But that's not the same order I have on GitHub since the issue on top of the widget should be the one opened on 25 October: https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue+label%3A%22Product-Hosts+File+Editor%22+sort%3Acreated-desc

**Comment by dkbennett** [comment] 2023-11-08 02:09
Ok I understand the issue here. The issue is related to search query strings, which can have arbitrary sorting. We need to use the time observed to sort, not the time updated or created. When that fix is in, I will fix this issue.

**Comment by dkbennett** [comment] 2023-11-08 22:42
I can't actually repro this. I noticed in the widget configuration screenshot your input was: `https://github.com/microsoft/PowerToys`

However, you were expecting it to look like a custom query result, which it will not do when that is the input. 

I put in this as input to the widget Url:
`https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue+label%3A%22Product-Hosts+File+Editor%22+sort%3Acreated-desc`

And I got the exact same result search order as that link shows on GitHub in the browser.

The issues widget allows a query string as input and it uses that string for the search, but you have to put the search query string as the input URL in order for it to work. Otherwise it will show default ordered by created date across all issues.

Try pasting your exact search query Url into the widget and it should work as you expect.

**Comment by dkbennett** [comment] 2023-11-08 22:53
Reopening because I noticed the query string was in the configuration. I'm not sure why this is failing, when I do it, the results are correct, and when I look directly at the datastore queries, the results are correct. Perhaps this breaks over time and not right away. I'm going to leave it alone and let the query update for a bit and see what happens.

**Closed** 2023-12-01 18:23 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
