### ISSUE TITLE
Trying to add a new GitHub account doesn't appear to launch browser

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhomegithubextension#126] opened 2023-05-18 00:06 UTC
### Steps to reproduce the bug

Description
I am trying to go through the flow to add a new account on this device. Dev Home tells me to check my browser in the background, but it doesn't appear to actually initiate a connection to GitHub so that I can auth.

(The spacing also seems off in the message for that UI, see attached screenshot.)

### Expected result

I believe from looking at the repro, there are two issues happening here:
Clicking the sign in button did nothing initially until it was closed and re-opened.  I was seeing something similar and I debugged that and it looks like an adaptive cards issue.  
Clicking the sign in button does do something and show the wait for browser message, but browser doesn't start up.  I briefly saw this when I had multiple Edge browsers installed which I also see is the case in this repro.  Using this bug to track that.

let's make sure this isn't the same "extension crashes because it tries to load the asset files" problem.  Right now in the store, this is the experience you get on a fresh machine.

**Comment by vineeththomasalex** [comment] 2023-11-27 18:35
Looks like a duplicate of https://github.com/microsoft/devhome/issues/472

**Closed by vineeththomasalex** 2023-11-27 18:35 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Quality, Priority-1, Area-Account-Sign-In
