### ISSUE TITLE
PR widget doesn't support draft or status filters 

### ISSUE THREAD

**Issue by krschau** [microsoft/devhomegithubextension#280] opened 2023-11-17 20:28 UTC
### Dev Home version

0.7

### Steps to reproduce the bug

Try the query https://github.com/microsoft/devhome/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+status%3Asuccess+-reviewed-by%3A%40me
is:pr is:open draft:false status:success -reviewedby:@me

### Actual result

The issues returned by github.com are different than what I see in Dev Home.

**Comment by krschau** [comment] 2023-11-17 20:29
@dkbennett FYI

**Comment by dkbennett** [comment] 2023-11-29 23:36
I believe this is because the issue request has some default assumptions. Need to be careful about fixing this but I suspect the correct fix is to trust the filter, even if it has closed or other such issues listed. Marking as P2 as the common case issues work correctly and only a subset of the filters that conflict with the base request are not working and that is more of an edge case.

**Comment by dkbennett** [comment] 2023-12-01 18:57
Oh this is the pull request widget, not the issues widget. The pull request widget does not support search query filters at all. However, if you change the URL link from: https://github.com/microsoft/devhome/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+status%3Asuccess+-reviewed-by%3A%40me   to  https://github.com/microsoft/devhome/issues?q=is%3Apr+is%3Aopen+draft%3Afalse+status%3Asuccess+-reviewed-by%3A%40me

And put it in the Issues widget, you get the correct result. This discrepency would be resolved by a proposed unification of the widgets since to GitHub pull requests and issues have the same underlying base (pull requests are a type of issue).

Since this can be done with the Issues widget, and the Pull Requests widget explicitly does not support query filters by design, I am closing this issue.

**Closed by dkbennett** 2023-12-01 18:57 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
