### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhomegithubextension#273] opened 2023-11-12 04:34 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Note: You should have an extension installed
Go to Extensions>Manage Extension

### Expected result

It should show that menu.

### Actual result

It was blank.

### Included System Information

Physical Memory: 11.89GB (2.06GB free)
Processor Architecture: x64

**Comment by krschau** [comment] 2023-11-14 18:42
Duplicate of https://github.com/microsoft/devhome/issues/1638

We'll need to do more investigation to know for sure which repo is the right place, but I'd rather have one issue to track.

**Closed by krschau** 2023-11-14 18:42 UTC
Labels: Issue-Bug, Needs-Triage
