### ISSUE TITLE
Windows widget BUG

### ISSUE THREAD

**Issue by Doraemon-byte** [microsoft/devhomegithubextension#191] opened 2023-06-19 07:16 UTC
### Dev Home version

0.200.165.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Add the "Mentioned me" component in the Windows11 widget
2. Select the desired option and click "Submit"

### Expected result

It is expected to display links about me in the account like the dashboard in the app

### Actual result

Only my account name is displayed, no links about me are displayed

### Included System Information

CPU: AMD Ryzen 5 5600U with Radeon Graphics         
Physical Memory: 13.84GB (6.86GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-19 17:58
@Doraemon-byte Do you have any PRs where your review is requested right now? If the list should be empty, this is a duplicate of https://github.com/microsoft/devhomegithubextension/issues/161. If there are PRs that should be there, it's a separate issue.

**Comment by Doraemon-byte** [comment] 2023-06-19 18:28
> 



> @Doraemon-byte你现在有任何要求你评论的PR吗？如果列表为空，则这是#161的副本。如果有公关应该在那里，这是一个单独的问题。



> @Doraemon-byte Do you have any PRs where your review is requested right now? If the list should be empty, this is a duplicate of #161. If there are PRs that should be there, it's a separate issue.

There is @my PR in the account. This component can normally list and mention my PR in the application, but when I put it into the "widget" function on the Windows taskbar, it will only display my account name without listing PR

**Comment by krschau** [comment] 2023-06-21 15:03
Hi @Doraemon-byte. It looks like this is a duplicate of #181. This specific instance is being closed in favor of the linked issue. Please add your 👍 to the other issue to raise its priority. Thanks for your contribution!

**Comment by krschau** [comment] 2023-06-21 15:03
Duplicate of #181

**Closed by krschau** 2023-06-21 15:03 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Team-Response
