### ISSUE TITLE
Extension not detected while trying to log-in

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhomegithubextension#272] opened 2023-11-12 04:29 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Try to log in.

### Expected result

It should log in because I have an extension installed.

### Actual result

It said this " No extension detected that wants your developer account while trying to login " ( Or something like that I don't remember ).

### Included System Information

Physical Memory: 11.89GB (2.06GB free)
Processor Architecture: x64

**Comment by krschau** [comment] 2023-11-14 18:44
Duplicate of https://github.com/microsoft/devhome/issues/1729

**Closed by krschau** 2023-11-14 18:44 UTC
Labels: Issue-Bug, Needs-Triage
