### ISSUE TITLE
can't login github

### ISSUE THREAD

**Issue by IPONCUY** [microsoft/devhomegithubextension#279] opened 2023-11-17 13:57 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

I can't login to Github

### Actual result

I can't login to github in DevHome it doesn't work

### Included System Information

Physical Memory: 5.85GB (1.04GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by jamescurran** [comment] 2023-11-17 19:25
Here are my log files
[DevHome.zip](https://github.com/microsoft/devhomegithubextension/files/13395687/DevHome.zip)
[DevHomeGitHubExtension.zip](https://github.com/microsoft/devhomegithubextension/files/13395688/DevHomeGitHubExtension.zip)

**Comment by vineeththomasalex** [comment] 2023-11-27 17:53
@jamescurran  Does this persist after you close and reopen the Login message box popup?

**Comment by vineeththomasalex** [comment] 2023-12-11 11:21
This is likely a duplicate of #108

@IPONCUY  Please reopen with logs if you continue to face this after reopening the messagebox.

**Closed by vineeththomasalex** 2023-12-11 11:21 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Account-Sign-In
